// react_frontend/src/pages/TodoPage.tsx
import React, { useEffect, useState } from "react"
import TodoItem from "../components/TodoItem"
import { delete_, get, post } from "../functions/fetch_helper"

type ITodoItem = {
    id: number
    content: string
}

export default function TodoPage(): JSX.Element {
    const [newTodoText, setNewTodoText] = useState("")
    const [todos, setTodos] = useState<ITodoItem[]>([])
    const [APIserverIsResponding, setAPIserverIsResponding] = useState(true)

    useEffect(() => {
        getTodos()
    }, [])

    const getTodos = async () => {
        try {
            const response = await get("/api")
            if (response.ok) {
                setTodos(await response.json())
                setAPIserverIsResponding(true)
                // console.log(`Response is: ${JSON.stringify(cards)}`);
            } else {
                throw new Error(response.statusText)
            }
        } catch {
            setAPIserverIsResponding(false)
        }
    }

    const submitPressed = async () => {
        /*
        To add optional search params, use:
        let params = new URLSearchParams("")
        params.set("mykey", "myvalue")
        fetch(`/api/${newTodo}?` + params.toString(), requestOptions)
         */
        if (APIserverIsResponding) {
            await post(`/api/${newTodoText}`)
        } else {
            localSubmit()
        }
        setNewTodoText("")
        await getTodos()
    }

    const submitPressedBody = async () => {
        if (APIserverIsResponding) {
            await post("/api_body", {
                new_todo: newTodoText,
            })
        } else {
            localSubmit()
        }
        setNewTodoText("")
        await getTodos()
    }

    const submitPressedModel = async () => {
        if (APIserverIsResponding) {
            const response = await post("/api_model", {
                todo_description: newTodoText,
            })
            if (!response.ok) {
                // If error, then you can debug here and see which fields were missing/expected
                const body = await response.text()
                console.log(body)
            }
        } else {
            localSubmit()
        }
        setNewTodoText("")
        await getTodos()
    }

    const removeTodo = async (id: number) => {
        if (APIserverIsResponding) {
            await delete_(`/api/${id}`)
        } else {
            localRemove(id)
        }
        await getTodos()
    }

    const localSubmit = () => {
        // Add an item to local todolist
        let maxIndex = 0
        todos.forEach((todo) => {
            maxIndex = Math.max(todo.id, maxIndex)
        })
        setTodos([...todos, { id: maxIndex + 1, content: newTodoText }])
        setNewTodoText("")
    }

    const localRemove = (id: number) => {
        // Remove an item from local todolist
        const index = todos.findIndex((obj) => {
            return obj.id === id
        })
        if (index >= 0) {
            setTodos([...todos.slice(undefined, index), ...todos.slice(index + 1)])
        }
    }

    // Render UI
    const todoTextInput = (
        <input
            id="newTodoInput"
            className="border-2 my-2 mx-1"
            type="text"
            onChange={(e) => {
                setNewTodoText(e.target.value)
            }}
            value={newTodoText}
            placeholder="My new todo item"
        />
    )

    const renderTodoItem = (todoItem: ITodoItem, index: number) => {
        return (
            <TodoItem
                index={index}
                id={todoItem.id}
                content={todoItem.content}
                deleteFunction={() => removeTodo(todoItem.id)}
                key={todoItem.id}
            />
        )
    }

    const renderApiServerResponding = APIserverIsResponding ? (
        ""
    ) : (
        <div className="bg-red-300 rounded p-1">Unable to connect to server - running local mode</div>
    )

    return (
        <div>
            <div className="flex flex-col items-center">
                <div className="flex">
                    {todoTextInput}
                    <button className="border-2 my-2 mx-1" id="submit1" onClick={submitPressed}>
                        Submit
                    </button>
                    <button className="border-2 my-2 mx-1" id="submit2" onClick={submitPressedBody}>
                        SubmitBody
                    </button>

                    <button className="border-2 my-2 mx-1" id="submit3" onClick={submitPressedModel}>
                        SubmitModel
                    </button>
                </div>
                {renderApiServerResponding}
            </div>

            <div className="grid grid-cols-1 justify-items-center ">
                <div>{todos.map(renderTodoItem)}</div>
            </div>
        </div>
    )
}

// svelte_frontend/src/pages/TodoPage.svelte
<script lang="ts">
    import { onMount } from 'svelte'
    import TodoCard from '../components/TodoCard.svelte'

    let newTodoText = ''
    let cards: { id: number; content: string }[] = [{ id: 0, content: 'some todo text' }]
    let APIserverIsResponding = true

    const api_server_ip = 'http://localhost:5000'

    onMount(async () => {
        // console.log("Loading todos")
        await getTodos()
    })

    const localSubmit = () => {
        // Add an item if server isnt responding
        let maxIndex = 0
        cards.forEach((card) => {
            maxIndex = Math.max(card.id, maxIndex)
        })
        maxIndex += 1
        cards = [...cards, { id: maxIndex, content: newTodoText }]
    }

    const localRemove = (id: number) => {
        // Remove an item if server isnt responding
        let obj = cards.find((obj) => {
            return obj.id === id
        })
        if (obj) {
            let index = cards.indexOf(obj)
            if (index >= 0) {
                cards = [...cards.slice(undefined, index), ...cards.slice(index + 1)]
            }
        }
    }

    const getTodos = async () => {
        APIserverIsResponding = true
        try {
            let response = await fetch(`${api_server_ip}/api`)
            if (response.ok) {
                cards = await response.json()
                // console.log(`Response is: ${JSON.stringify(cards)}`);
            } else {
                throw new Error(response.statusText)
            }
        } catch {
            APIserverIsResponding = false
        }
    }

    const submitPressed = async () => {
        /*
        To add optional search params, use:
        let params = new URLSearchParams("")
        params.set("mykey", "myvalue")
        fetch(`/api/${newTodo}?` + params.toString(), requestOptions)
         */
        try {
            await fetch(`${api_server_ip}/api/${newTodoText}`, {
                method: 'POST'
            })
        } catch {
            localSubmit()
        }
        newTodoText = ''
        await getTodos()
    }

    const submitPressedBody = async () => {
        // When using request body:
        try {
            const requestOptions = {
                method: 'POST',
                body: JSON.stringify({
                    new_todo: newTodoText
                })
            }
            await fetch(`${api_server_ip}/api_body`, requestOptions)
        } catch {
            localSubmit()
        }
        newTodoText = ''
        await getTodos()
    }

    const submitPressedModel = async () => {
        // When using request body:
        try {
            const requestOptions = {
                method: 'POST',
                body: JSON.stringify({
                    todo_description: newTodoText
                })
            }
            await fetch(`${api_server_ip}/api_model`, requestOptions)
        } catch {
            localSubmit()
        }
        newTodoText = ''
        await getTodos()
    }

    const removeTodo = async (id: number) => {
        try {
            await fetch(`${api_server_ip}/api/${id}`, {
                method: 'DELETE'
            })
        } catch {
            localRemove(id)
        }
        await getTodos()
    }
</script>

<main class="flex flex-column items-center">
    <div class="flex">
        <input
            id="newTodoInput"
            class="rounded my2 mx1"
            type="text"
            bind:value={newTodoText}
            placeholder="My new todo item"
        />
        <button class="rounded my2 mx1" id="submit1" on:click={submitPressed}>Submit</button>
        <button class="rounded my2 mx1" id="submit2" on:click={submitPressedBody}>SubmitBody</button>
        <button class="rounded my2 mx1" id="submit3" on:click={submitPressedModel}>SubmitModel</button>
    </div>
    {#if !APIserverIsResponding}
        <div class="bg-red-300 rounded p1">Unable to connect to server - running local mode</div>
    {/if}
    {#each cards as { id, content }, _i}
        <TodoCard cardText={content} index={id} {removeTodo} />
    {/each}
    <!-- Same as above -->
    <!-- {#each cards as card, i}
        <TodoCard cardText={card.content} index={card.id} {removeTodo} />
    {/each} -->
</main>
